# PhysMaster Configs

llm:
  base_url: "http://123.129.219.111:3000/v1"
  api_key: "sk-hnHVnUfqxBsPjGmC7EYAu5TWp9m31YqUJlPga0zulaqWRPTA"
  model: "gpt-5"

# Basics
pipeline:
  query_file: "instructions/CS_kernel_all_b_v23.txt"
  output_path: "outputs"
  parallel_processes: 3
  max_rounds: 24

mcts:
  draft_expansion: 2
  revise_expansion: 1
  exploration_constant: 1.414
  active_beam_width: 3

# Clarifier settings
clarifier:
  max_key_concpets: 5

skills:
  enabled: true
  roots:
    - "LANDAU/skills"

# LANDAU settings
landau:
  library_enabled: true
  library: "LANDAU/library"
  
  workflow_enabled: true
  workflow: "LANDAU/workflow"

  prior_enabled: false
  prior: "LANDAU/prior"

visualization:
  enabled: true
