# PhysMaster Configs

# Clarifier settings
clarifier:
  query_file: "instructions/test.txt"
  schema_file_path: "agent/clarifier/schema"
  output_path: "outputs"
  max_key_concpets: 5

# LANDAU settings
landau:
  library_enabled: true
  library: "LANDAU/library"
  
  workflow_enabled: true
  skills_enabled: true
  methodology: "LANDAU/methodology"

  prior_enabled: true
  prior: "LANDAU/prior"

pipeline:
  parallel_processes: 3
  max_nodes: 5
  complete_score_threshold: 0.7

mcts:
  draft_expansion: 2
  revise_expansion: 1
  improve_expansion: 1
  exploration_constant: 1.414
  beam_width: 3

visualization:
  enabled: true
